// <auto-generated />
namespace VehicleFinder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initalDatabase_CodeFirst_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initalDatabase_CodeFirst_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "201901212029578_initalDatabase_CodeFirst_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
